### ISSUE TITLE
Separate "Timed Race" and "Timed Trial" game modes

### ISSUE THREAD

**Issue by FauxBlue** [davidhcefx/Tracks-in-KartRider-Rush-Story-Mode#6]
Why are these two listed under the same abbreviation?

In Timed Trial (should be named "Time Challenge") you have to reach time gates to increase your remaining time and not get eliminated, whereas Timed Race is the same as a Speed Race but with a time limit. They are considerably different modes. If any should be grouped together it should be Timed Race and Speed Race.

**Comment by davidhcefx** [comment]
I forgot why I typed it as “Timed Trial”, but I think you’re right, I should have separated those two modes.

**Comment by FauxBlue** [comment]
Any preference for the abbreviations?

e.g.
| Mode| Abbr. |
| --- | --- |
| Timed Race | Tr |
| Time Challenge | Tc |

**Comment by FauxBlue** [comment]
Ah, wait. Was just going through these and found a "Time Trial", so there are actually 3 different time-related game modes.

For reference:
| Mode | First Chapter |
| --- | --- |
| Time Challenge | 2-5 |
| Timed Race | 1-1 |
| Time Trial | 7-2 |

Are you able to confirm which of the Chinese game mode names match up to each?

**Comment by davidhcefx** [comment]
> Any preference for the abbreviations?

Yeah that looks good. As for *Time trail*, perhaps `Tt`?

| Abbr. | En | Zh |
| ------ | -- | --- |
| Tc      | Time Challenge | 限時挑戰賽 |
| Tr      | Timed Race       | 限時賽 |
| Tt      | Time Trial          | 計時賽 |

**Comment by FauxBlue** [comment]
Thanks.

Similar, yes. I suppose that is why you combined them before. Also, there are only 3 Time Trials.

Time Trial is the normal Time Trial mode; essentially Speed Race without any opponents. Timed Race on the other hand is a Speed Race but with a time limit high enough that you shouldn't ever fail; not sure why they made that one.
