### ISSUE TITLE
Add karts

### ISSUE THREAD

**Issue by FauxBlue** [davidhcefx/Tracks-in-KartRider-Rush-Story-Mode#7]
On your [Reddit post](https://www.reddit.com/r/Kartrider/comments/t6lkb6/tracks_in_kartrider_rush_story_mode/?utm_source=share), you stated your motivation for this list was to help in practicing L1 tracks.  Since Story Mode doesn't give you a choice of karts, would listing the kart for each chapter also be useful?

e.g. for Cosmic Canyon (Northeu)
| **Chapter** | **Mode**         | **Kart**      |
|-------------|------------------|---------------|
| 12-6        | Speed Race       | Monster       |
| 24-6        | Elimination Race | Monster       |
| 41-6        | Speed Race       | White Knight  |
| 44-6        | Speed Race       | Dark Starfall |

**Comment by davidhcefx** [comment]
Yeah, absolutely. I have also described [here](https://github.com/davidhcefx/Tracks-in-KartRider-Rush-Story-Mode/discussions/3#discussion-3917813)

**Comment by FauxBlue** [comment]
Ah, sorry. I always forget to check discussions, I usually just look through open issues.
